// Auto-generated by ml/trainer.py — do not edit manually.
// Generated at: 2026-06-24T20:09:30.527516
// Best C: 0.1
// CV Mean F1: 0.6903
// CV Mean Precision: 0.5683
// CV Mean Recall: 0.8791
// CV Mean MCC: 0.6643

/// Number of features in the model.
pub const N_FEATURES: usize = 24;

/// Logistic regression coefficients (weights), one per feature.
pub const COEFFS: [f64; N_FEATURES] = [
    3.7587435566, -0.9004923612, 4.7172404496, 3.1795647544,
    0.6775949478, -7.9801370127, 0.1435360085, 0.9608306490,
    0.5556932334, -1.0503894138, -1.1488586597, -0.7137620688,
    -1.4003962099, 0.3428639442, 2.1145376077, -0.1159386950,
    0.0622758805, 0.2322111429, 0.1665737806, 0.0000000000,
    0.0000000000, 0.0000000000, 0.0000000000, 0.0000000000,
];

/// Logistic regression bias (intercept).
pub const BIAS: f64 = -13.2533834480;

/// Names of each feature (in order, matches COEFFS).
pub const FEATURE_NAMES: [&str; N_FEATURES] = [
    "entropy",
    "log_len",
    "digit_ratio",
    "upper_ratio",
    "lower_ratio",
    "special_ratio",
    "max_consecutive_repeat",
    "has_base64_padding",
    "has_colon",
    "has_slash",
    "has_dot",
    "has_hyphen",
    "has_underscore",
    "has_equals",
    "is_hex_only",
    "line_log_len",
    "keyword_count",
    "is_assignment",
    "has_quotes",
    "is_source_file",
    "is_config_file",
    "reserved_01",
    "reserved_02",
    "reserved_03"
];
